---
name: idr0139-lawson-fascin/screenC
version: 1

defaults:
  include: false
  type: string
  includeclient: true
  visible: true
  omitempty: true

columns:

  - name: Proprietary Compound
    clientname: Proprietary Compound
    include: true

  - name: Compound Concentration (microMolar)
    clientname: Compound Concentration (microMolar)
    include: true

  - name: Control Type
    clientname: Control Type
    include: true

  - name: Channels
    clientname: Channels
    include: true

  - name: Score
    clientname: Score
    include: true

  - name: Has Phenotype
    clientname: Has Phenotype
    include: true

  - name: Phenoptye Annotation Level
    clientname: Phenoptye Annotation Level
    include: true


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/cell_line/supplementary
      columns:
      - name: Comment [Cell Line]
        clientname: Cell Line Comment
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Comment [Gene Identifier]
        clientname: Gene Identifier
        include: yes
      - name: Comment [Gene Identifier]
        clientname: Gene Identifier URL
        clientvalue: https://www.ncbi.nlm.nih.gov/nuccore/{{ value|urlencode }}
        include: yes
      - name: Comment [Gene Symbol]
        clientname: Gene Symbol
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype
        clientname: Phenotype
        include: yes
      - name: Phenotype Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes


advanced:
  well_to_images: true
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
        - Phenotype
